---
output:
  github_document:
    html_preview: false
---

Install and load the R package.

```{r}
if(!requireNamespace('ROSCAR', quietly = TRUE)) {
  remotes::install_github('couthcommander/ROSCAR')
}
library(ROSCAR)
```

Generate some data (both RCT and OS). In this case, we'll introduce covariate mismatch.

```{r}
set.seed(2025)
dat <- simulate_rct_and_os_data(
  n_r = 300, n_o = 1000, support_fraction = 1/20,
  covariate_effect = c(Z = 2/3, V = 1),
  frac_U = 0.3, frac_V = 0.3
)
```

Take out necessary components.

```{r}
rct <- list(X = dat$X_RCT, Y = dat$y_r$y_observed, A = dat$a_r)
os <- list(X = dat$X_OS, Y = dat$y_o$y_observed, A = dat$a_o)
tau <- dat$y_r$tau
```

Run and evaluate models.

```{r}
mod <- cate_model(rct, os)
head(model_pred(mod))
model_eval(mod, tau)
```

Repeat with shared covariates.

```{r}
rct_sh <- rct
rct_sh[['X']] <- do.call(cbind, dat$components[c('U','Z_r')])
os_sh <- os
os_sh[['X']] <- do.call(cbind, dat$components[c('Z_o','V')])
mod_sh <- cate_model(rct_sh, os_sh)
model_eval(mod_sh, tau)
```

Try a quick experiment.

```{r}
iter <- 10
set.seed(iter)
l <- vector('list', iter)
for(i in seq_along(l)) {
  dat <- simulate_rct_and_os_data(n_r=250, n_o=500)
  rct <- list(X = dat$X_RCT, Y = dat$y_r$y_observed, A = dat$a_r)
  os <- list(X = dat$X_OS, Y = dat$y_o$y_observed, A = dat$a_o)
  mod <- cate_model(rct, os)
  l[[i]] <- model_eval(mod, dat$y_r$tau)
}
# mean RMSE for each method
rowMeans(vapply(l, \(i) i[,'rmse'], numeric(4)))
```
